### ISSUE TITLE
Shit EventBus

### ISSUE THREAD

**Issue by ghost** [The-Forecaster/Rush#1]
This is one of the worst attempts at a someone trying to look like a "pro" coder. You are using pointless interfaces that are used one time AND my brotha we all can see you trying to spread your trash over 3 different classes to try and pass it off of as a actually good EventManager.

**Comment by The-Forecaster** [comment]
not an issue

**Comment by Tarkan-Zarrouk** [comment]
lmao it is an issue, it's a shit event bus brov
